name: xhydro
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx
  - furo
  - mock
  - nbsphinx
  - pandoc
  - sphinx-autoapi
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinxcontrib-napoleon
