name: xhydro-dev
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.12
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  # Main packages
  - cartopy
  - geopandas
  - leafmap
  - numpy
  - pooch >=1.8.0
  - pydantic >=2.0,<2.5.3  # FIXME: Remove pin once our dependencies (xclim, xscen) support pydantic 2.5.3
  - pystac
  - rasterio
  - stackstac
  - statsmodels
  - tqdm
  - xagg
  - xarray
  - xclim >=0.47.0  # FIXME: Remove pin once our dependencies (xclim, xscen) support pandas 2.2.0
  - xscen >=0.7.1
  - pip >=23.3.0
  - pip:
    - flake8-alphabetize>=0.0.21  # development dependency
    - xdatasets
  # Dev
  - black ==24.1.1
  - blackdoc ==0.3.9
  - bump-my-version >=0.17.1
  - coverage >=6.2.2,<7.0.0
  - coveralls >=3.3.1
  - flake8 >=7.0.0
  - flake8-rst-docstrings>=0.3.0
  - furo
  - ipykernel
  - ipython
  - isort ==5.13.2
  - jupyter_client
  - nbsphinx
  - nbval
  - pandoc
  - planetary-computer
  - pooch
  - pre-commit >=3.3.2
  - pystac-client
  - ruff >=0.1.9
  - sphinx
  - sphinx-autoapi
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
  - sphinxcontrib-napoleon
  - stackstac
  - watchdog >=3.0.0
  # Testing
  - pytest >=7.3.1
  - pytest-cov >=4.0.0
  - tox >=4.5.1
  # Packaging
  - flit
  # Notebooks
  - hvplot
