name: xhydro-dev
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.12
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  # Main packages
  - numpy
  - pooch >=1.8.0
  - pydantic >=2.0,<2.5.3  # FIXME: Remove pin once our dependencies (xclim, xscen) support pydantic 2.5.3
  - spotpy
  - statsmodels
  - xarray
  - xclim >=0.45.0
  - xscen >=0.7.1
  - pip
  - pip:
    - xdatasets
  # Dev
  - bump-my-version >=0.12.0
  - coveralls
  - furo
  - ipykernel
  - ipython
  - jupyter_client
  - nbsphinx
  - nbval
  - pandoc
  - pooch
  - pre-commit
  - pytest
  - pytest-cov
  - sphinx
  - sphinx-autoapi
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
  - sphinxcontrib-napoleon
  # Testing
  - tox >=4.0
  # Packaging
  - flit
  # Notebooks
  - hvplot
