name: xhydro
channels:
  - conda-forge
dependencies:
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  - python >=3.9,<3.12
  - numpy
  - statsmodels
  - xarray
  - xclim >=0.45.0
  - xscen >=0.7.1
