name: xhydro-dev
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.13
  # Don't forget to sync changes between environment.yml, environment-dev.yml, and pyproject.toml!
  # Main packages
  - cartopy
  - geopandas
  - leafmap
  - numpy
  - pooch >=1.8.0
  - pydantic >=2.0,<2.5.3  # FIXME: Remove pin once our dependencies (xclim, xscen) support pydantic 2.5.3
  - pystac
  - rasterio
  - spotpy
  - stackstac
  - statsmodels
  - tqdm
  - xagg
  - xarray >=2023.11.0
  - xclim >=0.48.2
  - xscen >=0.8.3
  - pip >=23.3.0
  - pip:
    - flake8-alphabetize>=0.0.21  # development dependency
    - xdatasets >=0.3.5
  # Dev
  - black ==24.1.1
  - blackdoc ==0.3.9
  - bump-my-version >=0.18.3
#  - coveralls >=3.3.1
  - flake8 >=7.0.0
  - flake8-rst-docstrings>=0.3.0
  - furo
  - ipykernel
  - ipython
  - isort ==5.13.2
  - jupyter_client
  - nbsphinx
#  - nbval >=0.11.0
  - pandoc
  - planetary-computer
  - pooch
  - pre-commit >=3.3.2
  - pystac-client
  - ruff >=0.2.0
  - sphinx
  - sphinx-autoapi
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-intl
  - sphinxcontrib-napoleon
  - stackstac
  - watchdog >=3.0.0
  # Testing
  - pytest >=8.0.0
#  - pytest-cov >=4.0.0
  - tox >=4.5.1
  # Packaging
  - flit
  # Notebooks
  - hvplot
  - pip
  - pip:
    - coverage  # Not available in conda-forge for Python3.12
    - coveralls
    - pytest-cov >=4.0.0
    - nbval >=0.11.0
