name: xhydro
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx
  - pandoc
  - sphinx_rtd_theme >=1.0
  - sphinx-autoapi
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinxcontrib-napoleon
