name: "Bump Patch Version"

on:
  push:
    branches:
      - master
    paths-ignore:
      - .cruft.json
      - .editorconfig
      - .github/**.yml
      - .gitignore
      - .pre-commit-config.yaml
      - .yamllint.yaml
      - AUTHORS.rst
      - CHANGES.rst
      - CONTRIBUTING.rst
      - MANIFEST.in
      - Makefile
      - docs/*.py
      - docs/*.rst
      - docs/notebooks
      - environment.yml
      - requirements_dev.txt
      - setup.cfg
      - setup.py
      - tests/**.py
      - tox.ini
      - xhydro/__init__.py

jobs:
  bump_patch_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Config Commit Bot
        run: |
          git config --local user.email "bumpversion[bot]@hydrologie.com"
          git config --local user.name "bumpversion[bot]"
      - name: Current Version
        run: echo "current_version=$(grep -E '__version__'  xhydro/__init__.py | cut -d ' ' -f3)"
      - name: Bump Patch Version
        run: |
          pip install bump2version
          echo "Bumping version"
          bump2version patch
          echo "new_version=$(grep -E '__version__'  xhydro/__init__.py | cut -d ' ' -f3)"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          force: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
