name: "Bump Patch Version"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .cruft.json
      - .editorconfig
      - .github/**.yml
      - .gitignore
      - .pre-commit-config.yaml
      - .readthedocs.yml
      - .yamllint.yaml
      - .zenodo.json
      - AUTHORS.rst
      - CHANGES.rst
      - CONTRIBUTING.rst
      - Makefile
      - docs/*.py
      - docs/*.rst
      - docs/notebooks
      - environment-dev.yml
      - environment.yml
      - pyproject.toml
      - tests/**.py
      - tox.ini
      - xhydro/__init__.py
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bump_patch_version:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.9"
      - name: Config Commit Bot
        run: |
          git config --local user.email "bumpversion[bot]@hydrologie.com"
          git config --local user.name "bumpversion[bot]"
      - name: Current Version
        run: echo "current_version=$(grep -E '__version__'  xhydro/__init__.py | cut -d ' ' -f3)"
      - name: Bump Patch Version
        run: |
          pip install bump-my-version
          echo "Bumping version"
          bump-my-version bump --tag patch
          echo "new_version=$(grep -E '__version__'  xhydro/__init__.py | cut -d ' ' -f3)"
      - name: Push Changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          force: false
          github_token: ${{ secrets.BUMP_VERSION_TOKEN }}
          branch: ${{ github.ref }}
